name: genmed_2026
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - fastqc
  - bwa
  - samtools
  - bcftools
  - bedtools
  - r-base=4.2
  - r-tidyverse
  - jupyterlab
  - notebook
  - pip
  - pip:
      - nbformat
